### ISSUE TITLE
Unable to start correctly - Error loading script dist/server/build.js in resource oxmysql: TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by nc-jeni** [overextended/oxmysql#200]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [X] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [X] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**

[      script:oxmysql] Error loading script dist/server/build.js in resource oxmysql: TypeError [ERR_INVALID_URL]: Invalid URL
[      script:oxmysql] stack:
[      script:oxmysql] TypeError: Invalid URL
[      script:oxmysql]     at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
[      script:oxmysql]     at new NodeError (node:internal/errors:371:5)
[      script:oxmysql]     at onParseError (node:internal/url:552:9)
[      script:oxmysql]     at new URL (node:internal/url:628:5)
[      script:oxmysql]     at Function.parseUrl (@oxmysql/dist/server/build.js:14268:27)
[      script:oxmysql]     at new ConnectionConfig (@oxmysql/dist/server/build.js:14130:47)
[      script:oxmysql]     at new PoolConfig (@oxmysql/dist/server/build.js:15210:33)
[      script:oxmysql]     at Object.exports.createPool (@oxmysql/dist/server/build.js:15507:33)
[      script:oxmysql]     at createPool2 (@oxmysql/dist/server/build.js:15872:29)
[      script:oxmysql]     at src/server/db/pool.js (@oxmysql/dist/server/build.js:16011:42)
[      script:oxmysql]     at __init (@oxmysql/dist/server/build.js:23:56)
[      script:oxmysql]     at src/server/db/execute.js (@oxmysql/dist/server/build.js:16031:5)
[      script:oxmysql]     at __init (@oxmysql/dist/server/build.js:23:56)
[      script:oxmysql]     at @oxmysql/dist/server/build.js:16259:1

**Screenshots**

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by nc-jeni** [comment]
The problems to be that I had illegal characters in the connection string.
I changed the password to a strong version without symbols.
