### ISSUE TITLE
Dont know what it means but need some help

### ISSUE THREAD

**Issue by spanxurazz** [overextended/oxmysql#207]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x ] I am using the latest release
- [x ] I have referenced previously reported issues
- [ x] I have referenced available documentation and cannot resolve the issue
- [ x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
(node:2153326) UnhandledPromiseRejectionWarning: Error: Access denied for user 'zap1143401-1'@'185.249.196.47' (using password: YES)
    at Packet.asError (@oxmysql/dist/build.js:11535:21)
    at ClientHandshake.execute (@oxmysql/dist/build.js:13970:30)
    at PoolConnection.handlePacket (@oxmysql/dist/build.js:17428:38)
    at PacketParser.onPacket (@oxmysql/dist/build.js:17124:16)
    at PacketParser.executeStart (@oxmysql/dist/build.js:11760:20)
    at Socket.<anonymous> (@oxmysql/dist/build.js:17131:29)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
(Use `FXServer --trace-warnings ...` to show where the warning was created)
(node:2153326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2153326) UnhandledPromiseRejectionWarning: Error: Access denied for user 'zap1143401-1'@'185.249.196.47' (using password: YES)
    at Packet.asError (@oxmysql/dist/build.js:11535:21)
    at ClientHandshake.execute (@oxmysql/dist/build.js:13970:30)
    at PoolConnection.handlePacket (@oxmysql/dist/build.js:17428:38)
    at PacketParser.onPacket (@oxmysql/dist/build.js:17124:16)
    at PacketParser.executeStart (@oxmysql/dist/build.js:11760:20)
    at Socket.<anonymous> (@oxmysql/dist/build.js:17131:29)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
(node:2153326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2153326) UnhandledPromiseRejectionWarning: Error: Access denied for user 'zap1143401-1'@'185.249.196.47' (using password: YES)
    at Packet.asError (@oxmysql/dist/build.js:11535:21)
    at ClientHandshake.execute (@oxmysql/dist/build.js:13970:30)
    at PoolConnection.handlePacket (@oxmysql/dist/build.js:17428:38)
    at PacketParser.onPacket (@oxmysql/dist/build.js:17124:16)
    at PacketParser.executeStart (@oxmysql/dist/build.js:11760:20)
    at Socket.<anonymous> (@oxmysql/dist/build.js:17131:29)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
(node:2153326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:2153326) UnhandledPromiseRejectionWarning: Error: Access denied for user 'zap1143401-1'@'185.249.196.47' (using password: YES)
    at Packet.asError (@oxmysql/dist/build.js:11535:21)
    at ClientHandshake.execute (@oxmysql/dist/build.js:13970:30)
    at PoolConnection.handlePacket (@oxmysql/dist/build.js:17428:38)
    at PacketParser.onPacket (@oxmysql/dist/build.js:17124:16)
    at PacketParser.executeStart (@oxmysql/dist/build.js:11760:20)
    at Socket.<anonymous> (@oxmysql/dist/build.js:17131:29)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
(node:2153326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:2153326) UnhandledPromiseRejectionWarning: Error: Access denied for user 'zap1143401-1'@'185.249.196.47' (using password: YES)
    at Packet.asError (@oxmysql/dist/build.js:11535:21)
    at ClientHandshake.execute (@oxmysql/dist/build.js:13970:30)
    at PoolConnection.handlePacket (@oxmysql/dist/build.js:17428:38)
    at PacketParser.onPacket (@oxmysql/dist/build.js:17124:16)
    at PacketParser.executeStart (@oxmysql/dist/build.js:11760:20)
    at Socket.<anonymous> (@oxmysql/dist/build.js:17131:29)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
(node:2153326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:2153326) UnhandledPromiseRejectionWarning: Error: Access denied for user 'zap1143401-1'@'185.249.196.47' (using password: YES)
    at Packet.asError (@oxmysql/dist/build.js:11535:21)
    at ClientHandshake.execute (@oxmysql/dist/build.js:13970:30)
    at PoolConnection.handlePacket (@oxmysql/dist/build.js:17428:38)
    at PacketParser.onPacket (@oxmysql/dist/build.js:17124:16)
    at PacketParser.executeStart (@oxmysql/dist/build.js:11760:20)
    at Socket.<anonymous> (@oxmysql/dist/build.js:17131:29)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
(node:2153326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:2153326) UnhandledPromiseRejectionWarning: Error: Access denied for user 'zap1143401-1'@'185.249.196.47' (using password: YES)
    at Packet.asError (@oxmysql/dist/build.js:11535:21)
    at ClientHandshake.execute (@oxmysql/dist/build.js:13970:30)
    at PoolConnection.handlePacket (@oxmysql/dist/build.js:17428:38)
    at PacketParser.onPacket (@oxmysql/dist/build.js:17124:16)
    at PacketParser.executeStart (@oxmysql/dist/build.js:11760:20)
    at Socket.<anonymous> (@oxmysql/dist/build.js:17131:29)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
(node:2153326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)

(node:2153326) UnhandledPromiseRejectionWarning: Error: Access denied for user 'zap1143401-1'@'185.249.196.47' (using password: YES)
    at Packet.asError (@oxmysql/dist/build.js:11535:21)
    at ClientHandshake.execute (@oxmysql/dist/build.js:13970:30)
    at PoolConnection.handlePacket (@oxmysql/dist/build.js:17428:38)
    at PacketParser.onPacket (@oxmysql/dist/build.js:17124:16)
    at PacketParser.executeStart (@oxmysql/dist/build.js:11760:20)
    at Socket.<anonymous> (@oxmysql/dist/build.js:17131:29)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
(node:2153326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)

This is my issue

**Screenshots**

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**
I honestly expected it to run like previous versions

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB
- Version: Latest

**Comment by thelindat** [comment]
> Access denied for user 'zap1143401-1'@'185.249.196.47' (using password: YES)
