### ISSUE TITLE
Coudln't select by order

### ISSUE THREAD

**Issue by ONyambura** [overextended/oxmysql#24]
version '1.4.0'
```lua
        local query = exports.oxmysql:fetchSync("SELECT id, name, reward FROM gas_station_jobs WHERE gas_station_id = @gas_station_id AND progress = 0 ORDER BY id ASC", {
            ["@gas_station_id"] = gsID
        })
```
error
```
[      script:oxmysql] Error calling system tick function in resource oxmysql: Error: Undefined parameter name
[      script:oxmysql] stack:
[      script:oxmysql] Error: Undefined parameter name
[      script:oxmysql]     at toArrayParams (webpack-internal:///./node_modules/named-placeholders/index.js:106:49)
[      script:oxmysql]     at compile (webpack-internal:///./node_modules/named-placeholders/index.js:153:12)
[      script:oxmysql]     at PoolConnection._resolveNamedPlaceholders (webpack-internal:///./node_modules/mysql2/lib/connection.js:530:17)
[      script:oxmysql]     at PoolConnection.query (webpack-internal:///./node_modules/mysql2/lib/connection.js:543:10)
[      script:oxmysql]     at eval (webpack-internal:///./node_modules/mysql2/lib/pool.js:149:14)
[      script:oxmysql]     at eval (webpack-internal:///./node_modules/mysql2/lib/pool.js:45:37)
[      script:oxmysql]     at processTicksAndRejections (internal/process/task_queues.js:75:11)
[      script:oxmysql]     at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:62:3)
[      script:oxmysql]     at citizen:/scripting/v8/timer.js:227:32
```

**Comment by dunak-debug** [comment]
You are passing parameter `name` with `nil` value

**Comment by 1A3Dev** [comment]
> You are passing parameter `name` with `nil` value

I'm also having this issue, it seems to be parsing the values after the commas as parameters like I have `SELECT count,item as name,price,label FROM shops WHERE ShopNumber = @id` however it some reason parses it as `SELECT count??? FROM shops WHERE ShopNumber = ?`

**Comment by 1A3Dev** [comment]
It seems to be caused due to an error in the named-placeholders+1.1.2.patch regex (the comma before the @)

**Comment by dunak-debug** [comment]
This comma is not the issue. It just specify OR statement for : or @

**Comment by 1A3Dev** [comment]
> This comma is not the issue. It just specify OR statement for : or @

The issue is the comma, I tested removing it and it fixed the issue. For even more proof here is the current regex https://regexr.com/668tu and here is with the comma removed https://regexr.com/668u7

**Comment by dunak-debug** [comment]
Oh sorry, you are right. My bad.
